// I could be generated by Astro.glob, that's basically how you put
// this together (but console.logging it out).
// In which case you'd want a way of excluding pages that you don't
// want in the BackNext structure, i.e. AC.

export const pages = [
  { pathname: "/00-09_site_administration", title: "Site administration" },
  { pathname: "/00-09_site_administration/01_about", title: "About" },
  {
    pathname: "/00-09_site_administration/01_about/01.01_colophon",
    title: "Colophon",
  },
  {
    pathname: "/00-09_site_administration/01_about/01.02_licence",
    title: "Licence",
  },
  {
    pathname: "/00-09_site_administration/01_about/01.03_privacy",
    title: "Privacy",
  },
  {
    pathname: "/00-09_site_administration/01_about/01.04_version",
    title: "Version",
  },
  {
    pathname: "/00-09_site_administration/01_about/01.05_changelog",
    title: "Changelog",
  },
  {
    pathname: "/00-09_site_administration/02_send_and_receive",
    title: "Send and receive",
  },
  {
    pathname: "/00-09_site_administration/02_send_and_receive/02.01_contact_me",
    title: "Contact me",
  },
  {
    pathname:
      "/00-09_site_administration/02_send_and_receive/02.02_mailing_list",
    title: "Mailing list",
  },
  {
    pathname: "/00-09_site_administration/02_send_and_receive/02.03_rss_feed",
    title: "RSS feed",
  },
  {
    pathname: "/00-09_site_administration/02_send_and_receive/02.04_github",
    title: "GitHub",
  },
  { pathname: "/00-09_site_administration/03_settings", title: "Settings" },
  {
    pathname: "/00-09_site_administration/03_settings/03.01_theme",
    title: "Theme",
  },
  {
    pathname: "/00-09_site_administration/03_settings/03.02_language",
    title: "Language",
  },
  {
    pathname: "/00-09_site_administration/04_give_me_money",
    title: "Give me money",
  },
  {
    pathname: "/00-09_site_administration/04_give_me_money/04.01_support_me",
    title: "Support me",
  },
  {
    pathname: "/00-09_site_administration/04_give_me_money/04.02_consulting",
    title: "Consulting",
  },
  // { pathname: "/404", title: "Four-oh-four" },
  // { pathname: "/10-19_concepts", title: "Concepts" },
  // { pathname: "/10-19_concepts/11_core", title: "Core concepts" },
  { pathname: "/10-19_concepts/11_core/11.01_home_page", title: "Home page" },
  {
    pathname: "/10-19_concepts/11_core/11.02_areas_and_categories",
    title: "Areas and categories",
  },
  { pathname: "/10-19_concepts/11_core/11.03_ids", title: "IDs" },
  { pathname: "/10-19_concepts/11_core/11.04_philosophy", title: "Philosophy" },
  { pathname: "/10-19_concepts/11_core/11.05_the_index", title: "The index" },
  {
    pathname: "/10-19_concepts/11_core/11.06_saving_files",
    title: "Saving files",
  },
  {
    pathname: "/10-19_concepts/11_core/11.07_keeping_notes",
    title: "Keeping notes",
  },
  { pathname: "/10-19_concepts/12_advanced", title: "Advanced concepts" },
  {
    pathname: "/10-19_concepts/12_advanced/12.01_managing_email",
    title: "Managing email",
  },
  {
    pathname: "/10-19_concepts/12_advanced/12.02_working_at_the_command_line",
    title: "Working at the command line",
  },
];
